export const PALETTE = {
  russet: '#78290f',
  gri: '#313630',
  orangeRed: '#ff7d00',
  platinum: '#e8e9eb',
  timberwolf: 'rgba(255, 236, 209, 0.6)',
  onyx: '#001524',
  sandy: '#ffecd1',
  punk: '#FF9E80',
  white: '#f9f9f9',
  green: '#15616d',
  grey: '#313630',
  nwar: '#000000',
  acvhan: '#fff',
  rouge: 'red',
  bloug: '#14213d',
};

export const Colors = {
  light: {
    text: PALETTE.onyx,
    background: PALETTE.white,
    tint: PALETTE.orangeRed,
    icon: PALETTE.onyx,
    tabIconDefault: PALETTE.timberwolf,
    tabIconSelected: PALETTE.orangeRed,
    surface: PALETTE.platinum,
    accent: PALETTE.sandy,
    green: PALETTE.green,
    greyDes: PALETTE.grey,
    textNormal: PALETTE.nwar,
    errorText: PALETTE.punk,
    noir: PALETTE.nwar,
    blond: PALETTE.acvhan,
    blou: PALETTE.bloug,
    azuvagh: PALETTE.rouge,
    globeu: PALETTE.russet
  },
  dark: {
    text: PALETTE.platinum,
    background: PALETTE.onyx,
    tint: PALETTE.orangeRed,
    icon: PALETTE.platinum,
    tabIconDefault: '#687076',
    tabIconSelected: PALETTE.orangeRed,
    surface: '#3d4244',
    accent: PALETTE.sandy,
    green: PALETTE.green,
    greyDes: PALETTE.grey,
    textNormal: PALETTE.acvhan,
    errorText: PALETTE.rouge,
    noir: PALETTE.nwar,
    blond: PALETTE.acvhan,
    blou: PALETTE.bloug,
    azuvagh: PALETTE.rouge,
    globeu: PALETTE.punk
  },
};
